sudo: required
language: generic 
services: 
  - docker
  
before_install: 
  - docker build -t vivianewu/docker-react -f Dockerfile.dev .

scripts: 
  - docker run -e CI=true vivianewu/docker-react npm run test
